export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  MY_COURSES: "/my-courses",
  MY_PURCHASES: "/my-purchases",
  COURSES: "/courses",
  COURSE_DETAIL: (id: string) => `/courses/${id}`,
  BLOG: "/blog",
  CAREER: "/career",
  CART: "/cart",
  CHECKOUT: "/checkout",
  INSTRUCTOR_COURSES: "/instructor/courses",
  INSTRUCTOR_CREATE_COURSE: "/instructor/courses/create",
  INSTRUCTOR_EDIT_COURSE: (id: string) => `/instructor/courses/edit/${id}`,
  DISCUSSION: "/instructor/discussions",
};
